# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WelcomeUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from MainScreen import Ui_ProductZilla



class Ui_Dialog(object):

    def MainScreen(self):
        self.window2 = QtWidgets.QMainWindow()
        self.ui = Ui_ProductZilla()
        self.ui.setupUi(self.window2)
        self.window2.show()

    def Close(self):
        sys.exit()

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1386, 866)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        Dialog.setFont(font)
        icon = QtGui.QIcon.fromTheme("QT")
        Dialog.setWindowIcon(icon)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(-1, -1, 1391, 900))
        self.frame.setStyleSheet("background-color:#95a5a6;\n"
"background-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(470, 220, 461, 121))
        self.label.setStyleSheet("font: 87 36pt \"Arial Black\";\n"
"color:rgb(223, 223, 223)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(440, 340, 531, 121))
        self.label_2.setStyleSheet("font: 75 48pt \"Segoe Print\";\n"
"color: rgb(255, 255, 255);\n"
"color: rgb(255, 234, 0);")
        self.label_2.setObjectName("label_2")
        self.startBtn = QtWidgets.QPushButton(self.frame)
        self.startBtn.setGeometry(QtCore.QRect(720, 660, 431, 91))
        self.startBtn.setStyleSheet("border-radius:40px;\n"
"background-color: rgb(119, 226, 5);\n"
"font: 22pt \"MS Reference Sans Serif\";\n"
"color:rgb(230, 230, 230)")
        self.startBtn.setObjectName("startBtn")

        self.startBtn.clicked.connect(self.MainScreen)
        self.startBtn.clicked.connect(Dialog.close)

        self.cancelBtn = QtWidgets.QPushButton(self.frame)
        self.cancelBtn.setGeometry(QtCore.QRect(200, 660, 431, 91))
        self.cancelBtn.setStyleSheet("border-radius:40px;\n"
"font: 22pt \"MS Reference Sans Serif\";\n"
"color:rgb(230, 230, 230);\n"
"background-color: rgb(255, 23, 2);")
        self.cancelBtn.setObjectName("cancelBtn")
        self.cancelBtn.clicked.connect(self.Close)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Product Zilla"))
        self.label.setText(_translate("Dialog", "WELCOME TO"))
        self.label_2.setText(_translate("Dialog", "Product Zilla"))
        self.startBtn.setText(_translate("Dialog", "Start"))
        self.cancelBtn.setText(_translate("Dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
